### ISSUE TITLE
Предложения по улучшению

### ISSUE THREAD

**Issue by evil-pechenka** [Rocky-04/grade_converter#1]
Огромное спасибо! Все оценки скачались.

На IMDB не залил — просто выдаёт ошибку.

Из того, что заметил:
1. Неправильно определяет папку куда скачиваю, например указал папку `Temp/1`, а скачивает просто в Temp.
2. Не понятно зачем совмещено скачивание и отправка на IMDB — почему нельзя просто указать скачанный файл. Например у меня IMDB вызывает ошибку, чтобы перезапустить надо снова скачать Кинопоиск. Зачем?
3. Не хватает прогресс-бара, не понятно делает программа что-то или нет.

Анонсировать можно на крупных пабликах: DTF, VC, Пикабу. Если нужно — готов помочь.

Готов помочь с тестированием. Оперативный контакт: Телеграм [@EvilPechenka](https://t.me/EvilPechenka)

**Comment by MaximusPanin** [comment]
Программа запускает какое то свое окно Chrome  не дает авторизоваться.

**Comment by Rocky-04** [comment]
> Программа запускает какое то свое окно Chrome и не дает авторизоваться.

Ошибка возникла при переносе на IMDB?

**Comment by Rocky-04** [comment]
> Огромное спасибо! Все оценки скачались.
> 
> На IMDB не залил — просто выдаёт ошибку.
> 
> Из того, что заметил:
> 
> 1. Неправильно определяет папку куда скачиваю, например указал папку `Temp/1`, а скачивает просто в Temp.
> 2. Не понятно зачем совмещено скачивание и отправка на IMDB — почему нельзя просто указать скачанный файл. Например у меня IMDB вызывает ошибку, чтобы перезапустить надо снова скачать Кинопоиск. Зачем?
> 3. Не хватает прогресс-бара, не понятно делает программа что-то или нет.
> 
> Анонсировать можно на крупных пабликах: DTF, VC, Пикабу. Если нужно — готов помочь.
> 
> Готов помочь с тестированием. Оперативный контакт: Телеграм [@EvilPechenka](https://t.me/EvilPechenka)

Спасибо за обратную связь!
Дам знать как исправлю замечания :)

**Comment by iShaVas** [comment]
> Неправильно определяет папку куда скачиваю, например указал папку Temp/1, а скачивает просто в Temp.

Кажется, именно в этом и проблема с ошибкой перед началом заливки оценок на imdb.

А конкретно, не хватает слеша перед названиями файлов:

![image](https://user-images.githubusercontent.com/6636944/183359083-49eb40f2-e41a-4ddb-9faa-dc3a1b7e8ab9.png)

Я бы исправил сам, но нет permissions, чтобы закоммитить даже в ветку...

**Comment by Rocky-04** [comment]
> > Неправильно определяет папку куда скачиваю, например указал папку Temp/1, а скачивает просто в Temp.
> 
> Кажется, именно в этом и проблема с ошибкой перед началом заливки оценок на imdb.
> 
> А конкретно, не хватает слеша перед названиями файлов:
> 
> ![image](https://user-images.githubusercontent.com/6636944/183359083-49eb40f2-e41a-4ddb-9faa-dc3a1b7e8ab9.png)
> 
> Я бы исправил сам, но нет permissions, чтобы закоммитить даже в ветку...

Спасибо! Поправил. Попробуйте, пожалуйста, еще раз.

**Comment by Rocky-04** [comment]
> Огромное спасибо! Все оценки скачались.
> 
> На IMDB не залил — просто выдаёт ошибку.
> 
> Из того, что заметил:
> 
> 1. Неправильно определяет папку куда скачиваю, например указал папку `Temp/1`, а скачивает просто в Temp.
> 2. Не понятно зачем совмещено скачивание и отправка на IMDB — почему нельзя просто указать скачанный файл. Например у меня IMDB вызывает ошибку, чтобы перезапустить надо снова скачать Кинопоиск. Зачем?
> 3. Не хватает прогресс-бара, не понятно делает программа что-то или нет.
> 
> Анонсировать можно на крупных пабликах: DTF, VC, Пикабу. Если нужно — готов помочь.
> 
> Готов помочь с тестированием. Оперативный контакт: Телеграм [@EvilPechenka](https://t.me/EvilPechenka)

1. Исправил ошибку с папкой для сохранения.
2. Добавил проверку если файл уже скачан
3. Прогресс-бар реализовал выводом сообщений в консоль)

Попробуйте, пожалуйста, протестировать еще раз.
Заранее спасибо!
