### ISSUE TITLE
Закрыть сессию

### ISSUE THREAD

**Issue by TyVik** [Rocky-04/grade_converter#2]
Что-то мне кажется, что в файле `chrome/session` хранится ваша сессия kinopoisk. Я б советовал удалить этот файл и заодно выйти из всех сессий средствами авторизации сайта.

**Comment by Rocky-04** [comment]
Да так и есть) 
Специально хранил сессию с пройденной recaptcha, что бы была больше вероятность её проскочить.
Понимаю что это не лучшее решение, но пока не придумал ничего лучше

**Comment by TyVik** [comment]
Хранить - ok, но не надо пушить в публичный репозиторий :)
