### ISSUE TITLE
Параметризировать ключи для kinopoiskapiunofficial.tech

### ISSUE THREAD

**Issue by TyVik** [Rocky-04/grade_converter#4]
Ключи для kinopoiskapiunofficial.tech вшиты глубоко в код, и чтобы их поменять надо копаться в исходниках. Это бывает неудобно при частом изменении. Предлагаю вынести их куда-нибудь в константы в самом начале файла или вообще в отдельный файл.

**Comment by Rocky-04** [comment]
Спасибо за совет! Реализую.
Но вообще планировалось что пользователям их менять не придется
