### ISSUE TITLE
does not import to IMDB

### ISSUE THREAD

**Issue by zhernoklov-sleepnumber** [Rocky-04/grade_converter#6]
https:/www.imdb.com/title/tt5013056 - возможно произошла ошибка. Должна быть оценка 7
https:/www.imdb.com/title/tt4425200 - возможно произошла ошибка. Должна быть оценка 7
https:/www.imdb.com/title/tt2239822 - возможно произошла ошибка. Должна быть оценка 7
all attempts to rate a movie ends with such error.
Thanks in advance!

**Comment by Rocky-04** [comment]
Fixed several bugs. Download the program again and try again, please.
